# Generated by Django 5.2.7 on 2025-10-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_Name', models.CharField(max_length=100)),
                ('Priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('Due_Date', models.DateField()),
                ('Status', models.CharField(choices=[('In Progress', 'In Progress'), ('Pending', 'Pending'), ('To Do', 'To Do'), ('Task Done', 'Task Done')], max_length=50)),
                ('Assigned_By', models.CharField(max_length=50)),
                ('Working_Hours', models.IntegerField()),
                ('Description', models.CharField(max_length=1000)),
                ('Discussion', models.CharField(max_length=1000)),
                ('Links', models.URLField()),
                ('Attachments', models.URLField()),
            ],
        ),
    ]
