# Generated by Django 5.2.7 on 2025-12-22 08:29

import datetime
import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_Name', models.CharField(max_length=100)),
                ('Priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('Due_Date', models.DateField()),
                ('Status', models.CharField(choices=[('In Progress', 'In Progress'), ('Pending', 'Pending'), ('To Do', 'To Do'), ('Task Done', 'Task Done')], max_length=50)),
                ('Assigned_By', models.CharField(max_length=50)),
                ('Working_Hours', models.IntegerField()),
                ('Description', models.CharField(max_length=1000)),
                ('Discussion', models.CharField(max_length=1000)),
                ('Links', models.URLField()),
                ('Attachments', models.URLField()),
                ('Total_Time', models.DurationField(default=datetime.timedelta(0))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.EmailField(max_length=254, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('project_lead', 'Project Lead'), ('user', 'User')], default='user', max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.CharField(max_length=100)),
                ('Company_Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=1000)),
                ('Due_Date', models.DateField(blank=True, null=True)),
                ('Est_Hour', models.IntegerField()),
                ('Priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('Links', models.URLField()),
                ('Attachments', models.URLField()),
                ('Status', models.CharField(choices=[('In Progress', 'In Progress'), ('Pending', 'Pending'), ('To Do', 'To Do'), ('Task Done', 'Task Done')], max_length=50)),
                ('Active', models.CharField(choices=[('View', 'View'), ('Edit', 'Edit'), ('Delete', 'Delete')], max_length=15)),
                ('Assigned_to', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_Time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('End_Time', models.DateTimeField(blank=True, null=True)),
                ('Duration', models.DurationField(blank=True, null=True)),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='work_track_admin.tasks')),
            ],
        ),
    ]
