# Generated by Django 5.2.7 on 2025-10-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_track_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.CharField(max_length=100)),
                ('Company_Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=1000)),
                ('Assigned_to', models.CharField(max_length=50)),
                ('Due_Date', models.DateField()),
                ('Est_Hour', models.IntegerField()),
                ('Priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('Links', models.URLField()),
                ('Attachments', models.URLField()),
                ('Status', models.CharField(choices=[('In Progress', 'In Progress'), ('Pending', 'Pending'), ('To Do', 'To Do'), ('Task Done', 'Task Done')], max_length=50)),
                ('Active', models.CharField(choices=[('View', 'View'), ('Edit', 'Edit'), ('Delete', 'Delete')], max_length=15)),
            ],
        ),
    ]
