# Generated by Django 5.2.7 on 2025-10-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_track_admin', '0002_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='Due_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
