# Generated by Django 5.2.7 on 2025-11-03 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_track_admin', '0003_alter_projects_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_Time', models.DateTimeField(blank=True, default=-19800, null=True)),
                ('End_Time', models.DateTimeField(blank=True, null=True)),
                ('Duration', models.DurationField(blank=True, null=True)),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_track_admin.tasks')),
            ],
        ),
    ]
