# Generated by Django 5.2.7 on 2026-01-14 06:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_track_admin', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_time',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task_time',
            name='Start_Time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='task_time',
            constraint=models.UniqueConstraint(condition=models.Q(('End_Time__isnull', True)), fields=('Task', 'user'), name='one_running_session_per_user_per_task'),
        ),
    ]
