# Generated by Django 5.2.7 on 2025-11-03 07:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_track_admin', '0004_task_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='Total_Time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='task_time',
            name='Task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='work_track_admin.tasks'),
        ),
    ]
