# Generated by Django 5.2.7 on 2026-02-02 15:27

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_track_admin', '0004_task_time_user_alter_task_time_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_time',
            name='Task',
        ),
        migrations.RemoveField(
            model_name='task_time',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='Assigned_to',
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('est_hour', models.IntegerField(default=0)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('links', models.URLField(blank=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='project_files/')),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Pending', 'Pending'), ('To Do', 'To Do'), ('Task Done', 'Task Done'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('active', models.CharField(choices=[('View', 'View'), ('Edit', 'Edit'), ('Delete', 'Delete')], default='View', max_length=15)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Pending', 'Pending'), ('To Do', 'To Do'), ('Task Done', 'Task Done'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('working_hours', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('discussion', models.TextField(blank=True)),
                ('links', models.URLField(blank=True)),
                ('attachments', models.URLField(blank=True)),
                ('total_time', models.DurationField(default=datetime.timedelta(0))),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='work_track_admin.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.DeleteModel(
            name='Task_Time',
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
        migrations.AddConstraint(
            model_name='tasktime',
            constraint=models.UniqueConstraint(condition=models.Q(('end_time__isnull', True)), fields=('task', 'user'), name='one_running_session_per_user_per_task'),
        ),
    ]
