# Generated by Django 5.2.7 on 2025-11-03 12:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_track_admin', '0005_tasks_total_time_alter_task_time_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_time',
            name='Start_Time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
