# Generated by Django 5.2.7 on 2025-11-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_track_admin', '0006_alter_task_time_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='projects',
            name='Assigned_to',
        ),
        migrations.AddField(
            model_name='projects',
            name='Assigned_to',
            field=models.ManyToManyField(blank=True, to='work_track_admin.user'),
        ),
    ]
