# Generated by Django 5.2.7 on 2025-11-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_track_admin', '0007_user_remove_projects_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='Assigned_to',
            field=models.ManyToManyField(blank=True, null=True, to='work_track_admin.user'),
        ),
    ]
